kind: pipeline
type: docker
name: Testing Python CI/CD


steps:
- name: Install and deploy
  image: deadtree101/netauto
  environment:
    MY_PASS:
      from_secret: MY_PASS
  commands:
# - pip3 install -r requirements.txt
  - python3 checkip.py

trigger:
  branch:
    exclude:
  #  - main
    - master
