kind: pipeline
type: docker
name: Testing Python CI/CD


steps:
#- name: Black Code Format Check
#  image: deadtree101/netauto
#  commands:
#  - black . --check
- name: Batfish Prechecks
  image: deadtree101/netauto
  commands:
  - python batfishcheck.py

- name: Check IP Interfaces
  image: deadtree101/netauto
#  environment:
#    MY_PASS:
#      from_secret: MY_PASS
  commands:
# - pip3 install -r requirements.txt
  - python3 checkip.py

trigger:
  branch:
    exclude:
    - master
