---
nxos:
  platform: nxos_ssh
  username: "cisco"
  password: "cisco"
  connection_options:
    napalm:
      platform: nxos_ssh
    ssh:
      extras:
        look_for_keys: False
        allow_agent: False
