name: Nautobot Trigger

on:
  repository_dispatch:
    types: [nautobot_event]

jobs:
  log_event:
    runs-on: ubuntu-latest
    steps:
      - name: Print the Event Payload
        run: echo "Payload: ${{ toJson(github.event.client_payload) }}"
